omega_node = [
    "Health & Household > Diet & Sports Nutrition > Endurance & Energy > Powders",
    "Health & Household > Vitamins, Minerals & Supplements > Antioxidants > Polyphenol > Flavonoids > Rutin",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Amino Acids > Carnitine",
    "Health & Household > Vitamins, Minerals & Supplements > Essential Fatty Acids > Omega Oils > Omega 3-6-9",
    "Health & Household > Vitamins, Minerals & Supplements > Essential Fatty Acids > Combinations",
    "Health & Household > Vitamins, Minerals & Supplements > Essential Fatty Acids > Black Currant Oil",
    "Health & Household > Vitamins, Minerals & Supplements > Royal Jelly",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Amino Acids > Beta-Alanine",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > 7 Keto",
    "Health & Household > Vitamins, Minerals & Supplements > Essential Fatty Acids > EPA",
    "Health & Household > Vitamins, Minerals & Supplements > Glandular Extracts > Spleen Extracts",
    "Health & Household > Vitamins, Minerals & Supplements > Collagen",
    "Health & Household > Vitamins, Minerals & Supplements > Digestive Supplements > Prebiotics",
    "Health & Household > Vitamins, Minerals & Supplements > Glandular Extracts > Thymus Extracts",
    "Health & Household > Vitamins, Minerals & Supplements > Antioxidants > CoQ10",
    "Health & Household > Vitamins, Minerals & Supplements > Digestive Supplements > Probiotics > Acidophilus",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Testosterone Boosters",
    "Health & Household > Vitamins, Minerals & Supplements > Hyaluronic Acid",
    "Health & Household > Diet & Sports Nutrition > Weight Loss > Supplements > Carb Blockers",
    "Health & Household > Vitamins, Minerals & Supplements > Essential Fatty Acids > DHA",
    "Health & Household > Vitamins, Minerals & Supplements > Essential Fatty Acids > Omega Oils > Omega-3",
    "Health & Household > Vitamins, Minerals & Supplements > Enzymes > Multi-Enzymes",
    "Health & Household > Vitamins, Minerals & Supplements > MCT Oil",
    "Health & Household > Vitamins, Minerals & Supplements > Herbal Supplements > Psyllium",
    "Health & Household > Vitamins, Minerals & Supplements > Essential Fatty Acids",
    "Health & Household > Vitamins, Minerals & Supplements > Essential Fatty Acids > Omega Oils",
    "Health & Household > Vitamins, Minerals & Supplements > Essential Fatty Acids > Omega Oils > Omega-6",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Pre-Workout > Powders",
    "Health & Household > Vitamins, Minerals & Supplements > Glandular Extracts > Liver Extracts",
    "Health & Household > Vitamins, Minerals & Supplements > Essential Fatty Acids > Omega Oils > Omega-9",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Amino Acids > L-Glutamine",
    "Health & Household > Vitamins, Minerals & Supplements > Essential Fatty Acids > Linseed Oil",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Amino Acids > L-Lysine",
    "Health & Household > Vitamins, Minerals & Supplements > Digestive Supplements",
    "Health & Household > Vitamins, Minerals & Supplements > Enzymes > Lipase",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Amino Acids > Taurine",
    "Health & Household > Vitamins, Minerals & Supplements > Antioxidants > Alpha Lipoic Acid",
    "Health & Household > Diet & Sports Nutrition > Endurance & Energy > Herbals",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Pre-Workout > Nitric Oxide Boosters",
    "Health & Household > Vitamins, Minerals & Supplements > Lipid > Lecithin",
    "Health & Household > Vitamins, Minerals & Supplements > Essential Fatty Acids > Krill Oils",
    "Health & Household > Vitamins, Minerals & Supplements > Antioxidants > DMAE",
    "Health & Household > Vitamins, Minerals & Supplements > Essential Fatty Acids > Fish Oil",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Amino Acids > L-Citrulline",
    "Health & Household > Vitamins, Minerals & Supplements > Chondroitin & Glucosamine > Chondroitin",
    "Health & Household > Vitamins, Minerals & Supplements > Antioxidants > Polyphenol > Flavonoids",
    "Health & Household > Vitamins, Minerals & Supplements > Lipid",
    "Health & Household > Vitamins, Minerals & Supplements > Antioxidants > Combinations",
    "Health & Household > Vitamins, Minerals & Supplements > Antioxidants > Polyphenol > Flavonoids > Quercetin",
    "Health & Household > Vitamins, Minerals & Supplements > Antioxidants > Polyphenol > Flavonoids > Bioflavonoids",
    "Health & Household > Diet & Sports Nutrition > Endurance & Energy > Supplements",
    "Health & Household > Diet & Sports Nutrition > Weight Loss > Supplements > Fiber",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Amino Acids > 5-HTP",
    "Health & Household > Vitamins, Minerals & Supplements > Glandular Extracts > Adrenal Extracts",
    "Health & Household > Vitamins, Minerals & Supplements > Antioxidants > Resveratrol",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Amino Acids > Acetyl-L-Carnitine",
    "Health & Household > Vitamins, Minerals & Supplements > Antioxidants > Lycopene",
    "Health & Household > Vitamins, Minerals & Supplements > Chondroitin & Glucosamine > Glucosamine",
    "Health & Household > Diet & Sports Nutrition > Weight Loss > Supplements",
    "Health & Household > Vitamins, Minerals & Supplements > Enzymes > Lactase",
    "Health & Household > Vitamins, Minerals & Supplements > Glandular Extracts",
    "Health & Household > Vitamins, Minerals & Supplements > Antioxidants > Lutein",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Amino Acids > L-Leucine",
    "Health & Household > Vitamins, Minerals & Supplements > Antioxidants > Astaxanthin",
    "Health & Household > Vitamins, Minerals & Supplements > Sleep Supplements",
    "Health & Household > Vitamins, Minerals & Supplements > Blended Vitamin & Mineral Supplements",
    "Health & Household > Vitamins, Minerals & Supplements > Antioxidants",
    "Health & Household > Diet & Sports Nutrition > Weight Loss > Appetite Control & Suppressants",
    "Health & Household > Vitamins, Minerals & Supplements > Enzymes > Bromelain",
    "Health & Household > Vitamins, Minerals & Supplements > Antioxidants > Beta Carotenes",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Weight Gainers",
    "Health & Household > Vitamins, Minerals & Supplements > Glandular Extracts > Thyroid Extracts",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Amino Acids > Creatine",
    "Health & Household > Vitamins, Minerals & Supplements > Digestive Supplements > Probiotics",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > L-Carnitine",
    "Health & Household > Vitamins, Minerals & Supplements > MSM",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Amino Acids",
    "Health & Household > Vitamins, Minerals & Supplements",
    "Health & Household > Vitamins, Minerals & Supplements > Essential Fatty Acids > Black Seed Oil",
    "Health & Household > Vitamins, Minerals & Supplements > Antioxidants > French Maritime Pine Bark Extract",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Electrolyte Replacements",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Fat Burners",
    "Health & Household > Vitamins, Minerals & Supplements > Enzymes",
    "Health & Household > Vitamins, Minerals & Supplements > Essential Fatty Acids > Flax Seed Oil",
    "Health & Household > Vitamins, Minerals & Supplements > Antioxidants > Carotenoids",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > CLA",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Amino Acids > L-Arginine",
    "Health & Household > Vitamins, Minerals & Supplements > Chondroitin & Glucosamine > Combinations",
    "Health & Household > Vitamins, Minerals & Supplements > Antioxidants > Polyphenol",
    "Health & Household > Diet & Sports Nutrition > Sports Nutrition > Amino Acids > BCAAs",
    "Health & Household > Diet & Sports Nutrition > Weight Loss > Supplements > Detox & Cleanse",
    "Health & Household > Vitamins, Minerals & Supplements > Digestive Supplements > Charcoal",
    "Health & Household > Vitamins, Minerals & Supplements > Amino Acids > Creatine > Flash Player",
    "Health & Household > Vitamins, Minerals & Supplements > Minerals > Magnesium > Flash Player"
]

pet_node = [
    "Pet Supplies > Reptiles & Amphibians > Handling Tools > Snake Hooks",
    "Pet Supplies > Dogs > Litter & Housebreaking > Pooper Scoopers & Bags > Pooper Scoopers",
    "Pet Supplies > Cats > Grooming > Dander Remover Sprays",
    "Pet Supplies > Cats > Health Supplies > Itch Remedies",
    "Pet Supplies > Cats > Treats > Catnip",
    "Pet Supplies > Horses > Grooming & Bathing Supplies > Coat Care",
    "Pet Supplies > Horses > Stable Supplies > Feeding & Watering Equipment",
    "Pet Supplies > Dogs > Crates, Houses & Pens > Accessories > Kennel Covers > Crate Covers",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Substrate > Sand",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Décor",
    "Pet Supplies > Cats > Litter & Housebreaking",
    "Pet Supplies > Small Animals > Houses & Habitats > Habitat Décor",
    "Pet Supplies > Reptiles & Amphibians > Habitat Décor > Waterfalls",
    "Pet Supplies > Horses > Stable Supplies > Stall & Muck Supplies",
    "Pet Supplies > Small Animals > Houses & Habitats > Bedding & Litter",
    "Pet Supplies > Cats > Grooming > Electric Clippers & Blades > Replacement Blades",
    "Pet Supplies > Dogs > Crates, Houses & Pens > Accessories > Crate Replacement Pans",
    "Pet Supplies > Birds > Birdcage Accessories > Birdcage Liners",
    "Pet Supplies > Reptiles & Amphibians > Shipping Supplies > Hot Packs",
    "Pet Supplies > Horses > Stable Supplies > Feeding & Watering Equipment > Watering Supplies",
    "Pet Supplies > Cats > Grooming > Shedding Tools",
    "Pet Supplies > Dogs > Training & Behavior Aids > Agility Equipment > Jumps",
    "Pet Supplies > Dogs > Memorials & Funerary",
    "Pet Supplies > Cats > Health Supplies > Digestive Remedies",
    "Pet Supplies > Reptiles & Amphibians > Habitat Décor > Wood",
    "Pet Supplies > Dogs > Training & Behavior Aids > Repellents > Sonic Repellents",
    "Pet Supplies > Cats > Litter & Housebreaking > Replacement Filters",
    "Pet Supplies > Reptiles & Amphibians > Shipping Supplies > Cold Packs",
    "Pet Supplies > Small Animals > Grooming > Nail Care",
    "Pet Supplies > Reptiles & Amphibians > Terrarium Bedding, Sand & Substrate > Bedding",
    "Pet Supplies > Dogs > Doors, Gates & Ramps",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Pumps & Filters > Air Pump Accessories",
    "Pet Supplies > Dogs > Toys",
    "Pet Supplies > Dogs > Carriers & Travel Products > Car Travel Accessories > Barriers",
    "Pet Supplies > Dogs > Litter & Housebreaking > Training Pads & Trays > Trays",
    "Pet Supplies > Horses > Health Supplies > Wound Care",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Heaters & Chillers",
    "Pet Supplies > Dogs > Collars, Harnesses & Leashes",
    "Pet Supplies > Dogs > Training & Behavior Aids > Repellents > Spray Repellents",
    "Pet Supplies > Cats > Health Supplies > Wormers",
    "Pet Supplies > Dogs > Toys > Ball Launchers",
    "Pet Supplies > Dogs > Training & Behavior Aids > Sonic Bark Deterrents",
    "Pet Supplies > Dogs > Beds & Furniture > Bed Liners",
    "Pet Supplies > Dogs > Carriers & Travel Products > Car Travel Accessories",
    "Pet Supplies > Horses > Grooming & Bathing Supplies > Curry Combs",
    "Pet Supplies > Cats > Litter & Housebreaking > Litter Waste Receptacle Refills",
    "Pet Supplies > Horses > Stable Supplies > Tack Care & Storage > Tack Storage",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Substrate > Gravel",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Décor > Decorative Rocks",
    "Pet Supplies > Dogs > Grooming > Dematting Tools > Rakes",
    "Pet Supplies > Horses > Health Supplies > Salt Licks",
    "Pet Supplies > Dogs > Litter & Housebreaking > Pooper Scoopers & Bags > Pooper Scooper Sets",
    "Pet Supplies > Horses > Health Supplies > Vitamins & Supplements",
    "Pet Supplies > Dogs > Training & Behavior Aids > Dog Treat Pouches",
    "Pet Supplies > Cats > Litter & Housebreaking > Litter Mats",
    "Pet Supplies > Birds > Birdcage Accessories > Bedding & Litter",
    "Pet Supplies > Horses > Stable Supplies > Tack Care & Storage > Tack Care",
    "Pet Supplies > Small Animals > Grooming > Deodorizers",
    "Pet Supplies > Birds > Birdcage Accessories",
    "Pet Supplies > Birds > Birdcage Accessories > Nests",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Cleaners > Algae Scrapers",
    "Pet Supplies > Dogs > Health Supplies > Surgery Recovery Suits",
    "Pet Supplies > Cats > Health Supplies > Supplements & Vitamins",
    "Pet Supplies > Reptiles & Amphibians > Terrarium Heat Lamps & Mats > Heat Mats",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Hoods",
    "Pet Supplies > Cats > Cat Doors, Steps, Nets & Pens > Balcony Nets",
    "Pet Supplies > Dogs > Grooming > Shower & Bath Supplies > Portable Bathtubs",
    "Pet Supplies > Dogs > Grooming",
    "Pet Supplies > Reptiles & Amphibians > Habitat Lighting",
    "Pet Supplies > Dogs > Crates, Houses & Pens > Accessories > Kennel Covers > Enclosure Covers",
    "Pet Supplies > Horses > Health Supplies > Vitamins & Supplements > Vitamins & Minerals",
    "Pet Supplies > Cats > Health Supplies > Relaxants",
    "Pet Supplies > Horses > Stable Supplies > Feeding & Watering Equipment > Feeding Supplies",
    "Pet Supplies > Dogs > Grooming > Shower & Bath Supplies",
    "Pet Supplies > Cats > Beds & Furniture > Scratcher Accessories & Parts",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Heaters & Chillers > Chillers",
    "Pet Supplies > Cats > Health Supplies > Dental Care",
    "Pet Supplies > Reptiles & Amphibians > Terrarium Accessories > Environmental Control",
    "Pet Supplies > Reptiles & Amphibians > Terrarium Covers",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Cleaners > Water Changers",
    "Pet Supplies > Reptiles & Amphibians > Terrarium Accessories",
    "Pet Supplies > Dogs > Training & Behavior Aids",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Cleaners > Gravel Cleaners",
    "Pet Supplies > Horses > Farrier Supplies > Horseshoes",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Décor > Backgrounds",
    "Pet Supplies > Horses > Farrier Supplies > Tools",
    "Pet Supplies > Cats > Litter & Housebreaking > Litter Scoops",
    "Pet Supplies > Cats > Litter & Housebreaking > Toilet Training Systems",
    "Pet Supplies > Dogs > Grooming > Claw Care",
    "Pet Supplies > Cats > Treats",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Pumps & Filters > Filters",
    "Pet Supplies > Dogs > Beds & Furniture",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Substrate",
    "Pet Supplies > Cats > Health Supplies > Hairball Remedy Pastes & Gels",
    "Pet Supplies > Reptiles & Amphibians > Habitat Décor > Rocks",
    "Pet Supplies > Horses > Grooming & Bathing Supplies > Hoof Picks",
    "Pet Supplies > Dogs > Training & Behavior Aids > Repellents",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Pumps & Filters > Water Pump Accessories",
    "Sports & Outdoors > Outdoor Recreation > Camping & Hiking > Backpacks, Bags & Accessories > Dog Backpacks",
    "Pet Supplies > Small Animals > Houses & Habitats",
    "Pet Supplies > Cats > Collars, Harnesses & Leashes > Accessories",
    "Pet Supplies > Dogs > Feeding & Watering Supplies > Nursing Supplies",
    "Pet Supplies > Dogs > Training & Behavior Aids > Tie-Outs & Stakes",
    "Pet Supplies > Cats > Grooming > Styptic Gels & Powders > Styptic Powders",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Pumps & Filters > Filter Accessories",
    "Pet Supplies > Reptiles & Amphibians > Terrarium Accessories > Environmental Control > Humidifiers",
    "Pet Supplies > Dogs > Training & Behavior Aids > Repellents > Repellent Mats",
    "Pet Supplies > Dogs > Health Supplies > DNA Tests",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Heaters & Chillers > Aquarium Heaters",
    "Pet Supplies > Dogs > Training & Behavior Aids > Agility Equipment > Poles",
    "Pet Supplies > Birds > Birdcage Accessories > Seed Guards & Catchers",
    "Pet Supplies > Cats > Flea & Tick Control",
    "Pet Supplies > Fish & Aquatic Pets > Medication & Health Supplies",
    "Pet Supplies > Dogs > Grooming > Grooming Wipes",
    "Pet Supplies > Birds > Birdcage Accessories > Bird Baths",
    "Pet Supplies > Dogs > Toys > Automatic Ball Launchers",
    "Pet Supplies > Cats > Collars, Harnesses & Leashes > Location & Activity Trackers",
    "Pet Supplies > Horses > Health Supplies > Hip & Joint Care",
    "Pet Supplies > Dogs > Apparel & Accessories > Necklaces & Pendants",
    "Pet Supplies > Birds > Feeding & Watering Supplies > Hand-Feeding Tools",
    "Pet Supplies > Horses > Health Supplies",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Cleaners",
    "Pet Supplies > Horses > Boots & Wraps > Wraps",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Test Kits",
    "Pet Supplies > Dogs > Apparel & Accessories",
    "Pet Supplies > Cats > Collars, Harnesses & Leashes > Harnesses",
    "Pet Supplies > Reptiles & Amphibians > Habitat Lighting > UVB Lights",
    "Pet Supplies > Dogs > Collars, Harnesses & Leashes > Leashes",
    "Pet Supplies > Fish & Aquatic Pets > Aquatic Plant Care > Fertilizers",
    "Pet Supplies > Birds > Birdcage Accessories > Bird Food Dispensers",
    "Pet Supplies > Reptiles & Amphibians > Habitat Décor > Hides",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Heaters & Chillers > Aquarium Heaters > Submersible Heaters",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Cleaners > Sponge Cleaners",
    "Pet Supplies > Cats > Grooming > Brushes & Combs > Flea Combs",
    "Pet Supplies > Birds > Feeding & Watering Supplies > Bird Feeders",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Lighting",
    "Pet Supplies > Dogs > Litter & Housebreaking > Replacement Filters > Carbon Filters",
    "Pet Supplies > Cats > Health Supplies > Skin & Coat Remedies",
    "Pet Supplies > Horses > Riding Equipment > Bits",
    "Pet Supplies > Birds > Birdcage Accessories > Bird Cage Covers",
    "Pet Supplies > Cats > Health Supplies > Antibiotics",
    "Pet Supplies > Dogs > Health Supplies > Anxiety Relief",
    "Pet Supplies > Reptiles & Amphibians > Habitat Décor > Plants",
    "Pet Supplies > Birds > Birdcage Accessories > Bird Perches",
    "Pet Supplies > Cats > Health Supplies > Eye Care",
    "Pet Supplies > Reptiles & Amphibians > Habitat Décor > Climbing Structures",
    "Pet Supplies > Dogs > Grooming > Deodorizers > Dry Shampoo",
    "Pet Supplies > Cats > Grooming > Grooming Tools",
    "Pet Supplies > Dogs > Carriers & Travel Products > Car Travel Accessories > Pet Seat Covers",
    "Pet Supplies > Dogs > Crates, Houses & Pens > Accessories > Crate Replacement Pans",
    "Pet Supplies > Dogs > Training & Behavior Aids > Dog Training Collars",
    "Pet Supplies > Dogs > Apparel & Accessories > Costumes",
    "Pet Supplies > Dogs > Crates, Houses & Pens > Accessories > Crate Covers",
    "Pet Supplies > Reptiles & Amphibians > Habitat Lighting > LED Lights",
    "Pet Supplies > Reptiles & Amphibians > Terrarium Accessories > Environmental Control > Misting Systems",
    "Pet Supplies > Cats > Health Supplies > Anal Gland Care",
    "Pet Supplies > Cats > Health Supplies > Ear Care",
    "Pet Supplies > Dogs > Toys > Fetch Toys",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Substrate > Decorative Gravel",
    "Pet Supplies > Birds > Birdcage Accessories > Bird Food",
    "Pet Supplies > Dogs > Carriers & Travel Products > Car Travel Accessories > Pet Car Seats",
    "Pet Supplies > Reptiles & Amphibians > Habitat Décor > Stones",
    "Pet Supplies > Dogs > Training & Behavior Aids > Agility Equipment > Tunnel",
    "Pet Supplies > Reptiles & Amphibians > Terrarium Accessories > Environmental Control > Thermometers",
    "Pet Supplies > Birds > Birdcage Accessories > Bird Treats",
    "Pet Supplies > Reptiles & Amphibians > Terrarium Accessories > Terrarium Covers",
    "Pet Supplies > Reptiles & Amphibians > Habitat Décor > Plant Holders",
    "Pet Supplies > Birds > Birdcage Accessories > Food & Water Dishes",
    "Pet Supplies > Reptiles & Amphibians > Habitat Décor > Decor",
    "Pet Supplies > Cats > Health Supplies > Grooming Aids",
    "Pet Supplies > Birds > Birdcage Accessories > Nesting Material",
    "Pet Supplies > Birds > Birdcage Accessories > Bird Bathing Supplies",
    "Pet Supplies > Birds > Birdcage Accessories > Bird Seed",
    "Pet Supplies > Fish & Aquatic Pets > Aquarium Heaters & Chillers > Aquarium Heaters > Inline Heaters",
    "Pet Supplies > Dogs > Health Supplies > Hip & Joint Care > Flash Player",
    "Pet Supplies > Dogs > Health Supplies > Supplements & Vitamins > Herbal Supplements",
    "Pet Supplies › Dogs › Health Supplies › Relaxants"
]

nk_node = [
    "Clothing, Shoes & Jewelry > Women > Clothing > Lingerie, Sleep & Lounge > Lingerie > Shapewear > Thigh Slimmers",
    "Clothing, Shoes & Jewelry > Women > Clothing > Lingerie, Sleep & Lounge > Lingerie",
    "Clothing, Shoes & Jewelry > Women > Clothing > Lingerie, Sleep & Lounge > Sleep & Lounge"
]
